//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H5Forms.Dtos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("H5Forms.Dtos.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckList label.
        /// </summary>
        internal static string CheckListLabel {
            get {
                return ResourceManager.GetString("CheckListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DropDown label.
        /// </summary>
        internal static string DropDownLabel {
            get {
                return ResourceManager.GetString("DropDownLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First option.
        /// </summary>
        internal static string FirstOption {
            get {
                return ResourceManager.GetString("FirstOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a text here.
        /// </summary>
        internal static string FreeTextDefaultText {
            get {
                return ResourceManager.GetString("FreeTextDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control  doesn&apos;t exist.
        /// </summary>
        internal static string InvalidControl {
            get {
                return ResourceManager.GetString("InvalidControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control type  doesn&apos;t exist.
        /// </summary>
        internal static string InvalidControlType {
            get {
                return ResourceManager.GetString("InvalidControlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation type doesn&apos;t exist.
        /// </summary>
        internal static string InvalidValidationType {
            get {
                return ResourceManager.GetString("InvalidValidationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be in range of {1} and {2}.
        /// </summary>
        internal static string LengthBetweenMessage {
            get {
                return ResourceManager.GetString("LengthBetweenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must have a min length of {1}.
        /// </summary>
        internal static string LengthFromMessage {
            get {
                return ResourceManager.GetString("LengthFromMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must have a max length of {1}.
        /// </summary>
        internal static string LengthToMessage {
            get {
                return ResourceManager.GetString("LengthToMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptionList label.
        /// </summary>
        internal static string OptionListLabel {
            get {
                return ResourceManager.GetString("OptionListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string OtherValue {
            get {
                return ResourceManager.GetString("OtherValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0}  is required.
        /// </summary>
        internal static string RequiredMessage {
            get {
                return ResourceManager.GetString("RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second option.
        /// </summary>
        internal static string SecondOption {
            get {
                return ResourceManager.GetString("SecondOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBox label.
        /// </summary>
        internal static string TextBoxLabel {
            get {
                return ResourceManager.GetString("TextBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third option.
        /// </summary>
        internal static string ThirdOption {
            get {
                return ResourceManager.GetString("ThirdOption", resourceCulture);
            }
        }
    }
}
